{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "auxarmory.fullname" . }}-db-migrate
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auxarmory.labels" . | nindent 4 }}
    app.kubernetes.io/name: migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
      labels:
        {{- include "auxarmory.labels" . | nindent 8 }}
        app.kubernetes.io/name: migration
        network.rger.dev/access-postgres: "true"
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-migrate
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          command:
            {{- toYaml .Values.migration.command | nindent 12 }}
          env:
            - name: NODE_ENV
              value: {{ .Values.global.nodeEnv | quote }}
          envFrom:
            - secretRef:
                name: {{ include "auxarmory.sharedSecretName" . }}
{{- end }}
