apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "auxarmory.sharedSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auxarmory.labels" . | nindent 4 }}
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: {{ .Values.global.onePassword.sharedItemPath | quote }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "auxarmory.webSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auxarmory.labels" . | nindent 4 }}
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: {{ .Values.web.onePassword.itemPath | quote }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "auxarmory.authSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auxarmory.labels" . | nindent 4 }}
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: {{ .Values.auth.onePassword.itemPath | quote }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "auxarmory.apiSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auxarmory.labels" . | nindent 4 }}
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: {{ .Values.api.onePassword.itemPath | quote }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "auxarmory.workerSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auxarmory.labels" . | nindent 4 }}
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: {{ .Values.worker.onePassword.itemPath | quote }}
