apiVersion: v1
kind: Service
metadata:
  name: {{ include "auxarmory.web.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auxarmory.labels" . | nindent 4 }}
    app.kubernetes.io/name: web
spec:
  selector:
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: {{ include "auxarmory.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "auxarmory.auth.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auxarmory.labels" . | nindent 4 }}
    app.kubernetes.io/name: auth
spec:
  selector:
    app.kubernetes.io/name: auth
    app.kubernetes.io/instance: {{ include "auxarmory.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.auth.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "auxarmory.api.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auxarmory.labels" . | nindent 4 }}
    app.kubernetes.io/name: api
spec:
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: {{ include "auxarmory.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
