apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-controller
  annotations:
    operator.1password.io/autorestart: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-controller
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-controller
    spec:
      serviceAccountName: {{ .Release.Name }}-controller-sa
      containers:
      - name: controller
        image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
        imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
        ports:
        - name: api
          containerPort: 3000
        - name: grpc
          containerPort: 50051
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: K8S_NAMESPACE
          value: {{ .Release.Namespace | quote }}
        {{- range $key, $value := .Values.controller.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range .Values.controller.secrets }}
        - name: {{ . }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Release.Name }}-secret
              key: {{ . }}
        {{- end }}
        {{- with .Values.controller.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}