{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-controller-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-controller-role
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-controller
rules:
{{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-controller-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-controller
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-controller-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-controller-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}