apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "redis.fullname" . }}
    component: redis
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
