apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  itemPath: "vaults/ksplpxkiblaftafiljqytehbcy/items/6aufq3n76f7jfezek2sfzr6lri"