cloudflared:
  image:
    repository: cloudflare/cloudflared
    tag: "2026.1.2"
    pullPolicy: IfNotPresent

  replicas: 2

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

  logLevel: info
  metricsPort: 2000

  podSecurityContext:
    runAsUser: 65532
    runAsNonRoot: true
    fsGroup: 65532

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
