{{- $onePassword := .Values.onePassword | default dict -}}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: {{ $onePassword.itemPath | default "vaults/ksplpxkiblaftafiljqytehbcy/items/postgres-cluster" | quote }}
