fullnameOverride: ""

image:
  repository: redis
  tag: "8.2.1-alpine"
  pullPolicy: IfNotPresent

service:
  port: 6379

storage:
  className: local-path
  size: 5Gi

nodeSelector:
  role: database

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"
