apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auxbot
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: deployments
    notifications.argoproj.io/subscribe.on-sync-failed.slack: deployments
    notifications.argoproj.io/subscribe.on-health-degraded.slack: deployments
    notifications.argoproj.io/subscribe.on-rollback.slack: deployments
    notifications.argoproj.io/subscribe.on-image-updated.slack: deployments
spec:
  project: default
  source:
    repoURL: https://github.com/Dumspy/k8s-manifest
    path: charts/auxbot
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
