apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auxbot
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: controller=ghcr.io/dumspy/auxbot-controller:latest
    argocd-image-updater.argoproj.io/controller.update-strategy: digest
    argocd-image-updater.argoproj.io/controller.helm.image-name: controller.image.repository
    argocd-image-updater.argoproj.io/controller.helm.image-tag: controller.image.tag
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: deployments
    notifications.argoproj.io/subscribe.on-sync-failed.slack: deployments
    notifications.argoproj.io/subscribe.on-deployed.slack: deployments
    notifications.argoproj.io/subscribe.on-health-degraded.slack: deployments
    notifications.argoproj.io/subscribe.on-sync-running.slack: deployments
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: deployments
    notifications.argoproj.io/subscribe.on-created.slack: deployments
    notifications.argoproj.io/subscribe.on-deleted.slack: deployments
    notifications.argoproj.io/subscribe.on-rollback.slack: deployments
    notifications.argoproj.io/subscribe.on-image-updated.slack: deployments
spec:
  project: default
  source:
    repoURL: https://github.com/Dumspy/k8s-manifest
    path: charts/auxbot
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
