apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base-app 
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: deployments
    notifications.argoproj.io/subscribe.on-sync-failed.slack: deployments
    notifications.argoproj.io/subscribe.on-deployed.slack: deployments
    notifications.argoproj.io/subscribe.on-health-degraded.slack: deployments
    notifications.argoproj.io/subscribe.on-sync-running.slack: deployments
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: deployments
    notifications.argoproj.io/subscribe.on-created.slack: deployments
    notifications.argoproj.io/subscribe.on-deleted.slack: deployments
    notifications.argoproj.io/subscribe.on-rollback.slack: deployments
spec:
  project: default
  source:
    repoURL: https://github.com/Dumspy/k8s-manifest
    path: argo-apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd