apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Dumspy/k8s-manifest
    path: manifest/hello-world
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: test
