apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-oci
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: deployments
    notifications.argoproj.io/subscribe.on-sync-failed.slack: deployments
    notifications.argoproj.io/subscribe.on-health-degraded.slack: deployments
spec:
  project: default
  source:
    repoURL: https://github.com/Dumspy/k8s-manifest
    path: charts/sample-app
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: oci-cluster
    namespace: sample-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
